// Code generated by 'make gen-errors'; DO NOT EDIT
package client

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrPathNotFound     = "ERR_KLEV_API_0001"
	ErrMethodNotAllowed = "ERR_KLEV_API_0002"
	ErrInvalidJson      = "ERR_KLEV_API_0003"
)

func IsErrPathNotFound(err error) bool {
	return errors.IsError(err, ErrPathNotFound)
}

func IsErrMethodNotAllowed(err error) bool {
	return errors.IsError(err, ErrMethodNotAllowed)
}

func IsErrInvalidJson(err error) bool {
	return errors.IsError(err, ErrInvalidJson)
}
