// Code generated by 'gen-objects'; DO NOT EDIT
package klev

import (
	"fmt"
)

type Subject string

const (
	SubjectEgressWebhooks  Subject = "egress_webhooks"
	SubjectFilters         Subject = "filters"
	SubjectIngressWebhooks Subject = "ingress_webhooks"
	SubjectLogs            Subject = "logs"
	SubjectMessages        Subject = "messages"
	SubjectOffsets         Subject = "offsets"
	SubjectTokens          Subject = "tokens"
)

type Action string

const (
	ActionCleanup Action = "cleanup"
	ActionConsume Action = "consume"
	ActionCreate  Action = "create"
	ActionDelete  Action = "delete"
	ActionGet     Action = "get"
	ActionList    Action = "list"
	ActionPublish Action = "publish"
	ActionRotate  Action = "rotate"
	ActionStatus  Action = "status"
	ActionUpdate  Action = "update"
)

func ACLSubject(subject Subject) string {
	return fmt.Sprintf("%s", subject)
}

func ACLAction(subject Subject, action Action) string {
	return fmt.Sprintf("%s:%s", subject, action)
}

func ACLObject(subject Subject, action Action, id string) string {
	return fmt.Sprintf("%s:%s:%s", subject, action, id)
}
