// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrACLActionInvalidObjectCode         = "acl-action-invalid-object"
	ErrACLActionMissingCode               = "acl-action-missing"
	ErrACLObjectEgressWebhookInvalidCode  = "acl-object-egress-webhook-invalid"
	ErrACLObjectFilterInvalidCode         = "acl-object-filter-invalid"
	ErrACLObjectIngressWebhookInvalidCode = "acl-object-ingress-webhook-invalid"
	ErrACLObjectLogInvalidCode            = "acl-object-log-invalid"
	ErrACLObjectOffsetInvalidCode         = "acl-object-offset-invalid"
	ErrACLObjectTokenInvalidCode          = "acl-object-token-invalid"
	ErrACLSubjectActionInvalidCode        = "acl-subject-action-invalid"
	ErrACLSubjectMissingCode              = "acl-subject-missing"
)

func IsErrACLActionInvalidObject(err error) bool {
	return IsError(err, ErrACLActionInvalidObjectCode)
}

func IsErrACLActionMissing(err error) bool {
	return IsError(err, ErrACLActionMissingCode)
}

func IsErrACLObjectEgressWebhookInvalid(err error) bool {
	return IsError(err, ErrACLObjectEgressWebhookInvalidCode)
}

func IsErrACLObjectFilterInvalid(err error) bool {
	return IsError(err, ErrACLObjectFilterInvalidCode)
}

func IsErrACLObjectIngressWebhookInvalid(err error) bool {
	return IsError(err, ErrACLObjectIngressWebhookInvalidCode)
}

func IsErrACLObjectLogInvalid(err error) bool {
	return IsError(err, ErrACLObjectLogInvalidCode)
}

func IsErrACLObjectOffsetInvalid(err error) bool {
	return IsError(err, ErrACLObjectOffsetInvalidCode)
}

func IsErrACLObjectTokenInvalid(err error) bool {
	return IsError(err, ErrACLObjectTokenInvalidCode)
}

func IsErrACLSubjectActionInvalid(err error) bool {
	return IsError(err, ErrACLSubjectActionInvalidCode)
}

func IsErrACLSubjectMissing(err error) bool {
	return IsError(err, ErrACLSubjectMissingCode)
}
