// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrACLInsufficientPermissions     = "ERR_KLEV_ACL_API_0001"
	ErrACLItemFormatInvalid           = "ERR_KLEV_ACL_API_0002"
	ErrACLSubjectInvalid              = "ERR_KLEV_ACL_API_0003"
	ErrACLActionInvalid               = "ERR_KLEV_ACL_API_0004"
	ErrACLObjectActionInvalid         = "ERR_KLEV_ACL_API_0005"
	ErrACLObjectTokenInvalid          = "ERR_KLEV_ACL_API_0006"
	ErrACLObjectLogInvalid            = "ERR_KLEV_ACL_API_0007"
	ErrACLObjectIngressWebhookInvalid = "ERR_KLEV_ACL_API_0008"
	ErrACLObjectOffsetInvalid         = "ERR_KLEV_ACL_API_0009"
	ErrACLObjectEgressWebhookInvalid  = "ERR_KLEV_ACL_API_0010"
	ErrACLObjectFilterInvalid         = "ERR_KLEV_ACL_API_0011"
)

func IsErrACLInsufficientPermissions(err error) bool {
	return IsError(err, ErrACLInsufficientPermissions)
}

func IsErrACLItemFormatInvalid(err error) bool {
	return IsError(err, ErrACLItemFormatInvalid)
}

func IsErrACLSubjectInvalid(err error) bool {
	return IsError(err, ErrACLSubjectInvalid)
}

func IsErrACLActionInvalid(err error) bool {
	return IsError(err, ErrACLActionInvalid)
}

func IsErrACLObjectActionInvalid(err error) bool {
	return IsError(err, ErrACLObjectActionInvalid)
}

func IsErrACLObjectTokenInvalid(err error) bool {
	return IsError(err, ErrACLObjectTokenInvalid)
}

func IsErrACLObjectLogInvalid(err error) bool {
	return IsError(err, ErrACLObjectLogInvalid)
}

func IsErrACLObjectIngressWebhookInvalid(err error) bool {
	return IsError(err, ErrACLObjectIngressWebhookInvalid)
}

func IsErrACLObjectOffsetInvalid(err error) bool {
	return IsError(err, ErrACLObjectOffsetInvalid)
}

func IsErrACLObjectEgressWebhookInvalid(err error) bool {
	return IsError(err, ErrACLObjectEgressWebhookInvalid)
}

func IsErrACLObjectFilterInvalid(err error) bool {
	return IsError(err, ErrACLObjectFilterInvalid)
}
