// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrACLActionInvalidCode  = "acl-action-invalid"
	ErrACLObjectMissingCode  = "acl-object-missing"
	ErrACLSubjectInvalidCode = "acl-subject-invalid"
)

func IsErrACLActionInvalid(err error) bool {
	return IsError(err, ErrACLActionInvalidCode)
}

func IsErrACLObjectMissing(err error) bool {
	return IsError(err, ErrACLObjectMissingCode)
}

func IsErrACLSubjectInvalid(err error) bool {
	return IsError(err, ErrACLSubjectInvalidCode)
}
