// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrPathNotFound     = "ERR_KLEV_API_0001"
	ErrMethodNotAllowed = "ERR_KLEV_API_0002"
	ErrInvalidJson      = "ERR_KLEV_API_0003"
)

func IsErrPathNotFound(err error) bool {
	return IsError(err, ErrPathNotFound)
}

func IsErrMethodNotAllowed(err error) bool {
	return IsError(err, ErrMethodNotAllowed)
}

func IsErrInvalidJson(err error) bool {
	return IsError(err, ErrInvalidJson)
}
