// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrJsonInvalidCode      = "json-invalid"
	ErrMethodNotAllowedCode = "method-not-allowed"
	ErrPathNotFoundCode     = "path-not-found"
)

func IsErrJsonInvalid(err error) bool {
	return IsError(err, ErrJsonInvalidCode)
}

func IsErrMethodNotAllowed(err error) bool {
	return IsError(err, ErrMethodNotAllowedCode)
}

func IsErrPathNotFound(err error) bool {
	return IsError(err, ErrPathNotFoundCode)
}
