// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrJsonInvalid      = "json-invalid"
	ErrMethodNotAllowed = "method-not-allowed"
	ErrPathNotFound     = "path-not-found"
)

func IsErrJsonInvalid(err error) bool {
	return IsError(err, ErrJsonInvalid)
}

func IsErrMethodNotAllowed(err error) bool {
	return IsError(err, ErrMethodNotAllowed)
}

func IsErrPathNotFound(err error) bool {
	return IsError(err, ErrPathNotFound)
}
