// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrAuthenticationFailed       = "authentication-failed"
	ErrAuthorizationFailed        = "authorization-failed"
	ErrAuthorizationHeaderInvalid = "authorization-header-invalid"
	ErrAuthorizationHeaderMissing = "authorization-header-missing"
	ErrContentTypeInvalid         = "content-type-invalid"
	ErrContentTypeMissing         = "content-type-missing"
	ErrSubscriptionMissing        = "subscription-missing"
)

func IsErrAuthenticationFailed(err error) bool {
	return IsError(err, ErrAuthenticationFailed)
}

func IsErrAuthorizationFailed(err error) bool {
	return IsError(err, ErrAuthorizationFailed)
}

func IsErrAuthorizationHeaderInvalid(err error) bool {
	return IsError(err, ErrAuthorizationHeaderInvalid)
}

func IsErrAuthorizationHeaderMissing(err error) bool {
	return IsError(err, ErrAuthorizationHeaderMissing)
}

func IsErrContentTypeInvalid(err error) bool {
	return IsError(err, ErrContentTypeInvalid)
}

func IsErrContentTypeMissing(err error) bool {
	return IsError(err, ErrContentTypeMissing)
}

func IsErrSubscriptionMissing(err error) bool {
	return IsError(err, ErrSubscriptionMissing)
}
