// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type EgressWebhookPayload struct{ string }

var (
	EgressWebhookPayloadMessage = EgressWebhookPayload{"message"}
	EgressWebhookPayloadKey     = EgressWebhookPayload{"key"}
	EgressWebhookPayloadValue   = EgressWebhookPayload{"value"}
)

var NilEgressWebhookPayload = EgressWebhookPayload{}

var AllEgressWebhookPayloads = []EgressWebhookPayload{
	EgressWebhookPayloadMessage,
	EgressWebhookPayloadKey,
	EgressWebhookPayloadValue,
}

func ParseEgressWebhookPayload(s string) (EgressWebhookPayload, error) {
	switch s {
	case "message":
		return EgressWebhookPayloadMessage, nil
	case "key":
		return EgressWebhookPayloadKey, nil
	case "value":
		return EgressWebhookPayloadValue, nil
	default:
		return NilEgressWebhookPayload, ErrEgressWebhookPayloadInvalid(s, "message, key, value")
	}
}

func (e EgressWebhookPayload) String() string {
	return e.string
}

func (e EgressWebhookPayload) MarshalText() ([]byte, error) {
	return []byte(e.string), nil
}

func (e *EgressWebhookPayload) UnmarshalText(text []byte) error {
	v, err := ParseEgressWebhookPayload(string(text))
	if err != nil {
		return err
	}

	*e = v
	return nil
}
