// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type EgressWebhookID string

func ParseEgressWebhookID(id string) (EgressWebhookID, error) {
	if err := validate(id, "ewh"); err != nil {
		return EgressWebhookID(""), err
	}
	return EgressWebhookID(id), nil
}
