// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrEgressWebhookCountLimited    = "egress-webhook-count-limited"
	ErrEgressWebhookMetadataLimited = "egress-webhook-metadata-limited"
	ErrEgressWebhookNotFound        = "egress-webhook-not-found"
	ErrEgressWebhookPayloadInvalid  = "egress-webhook-payload-invalid"
)

func IsErrEgressWebhookCountLimited(err error) bool {
	return IsError(err, ErrEgressWebhookCountLimited)
}

func IsErrEgressWebhookMetadataLimited(err error) bool {
	return IsError(err, ErrEgressWebhookMetadataLimited)
}

func IsErrEgressWebhookNotFound(err error) bool {
	return IsError(err, ErrEgressWebhookNotFound)
}

func IsErrEgressWebhookPayloadInvalid(err error) bool {
	return IsError(err, ErrEgressWebhookPayloadInvalid)
}
