// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrEgressWebhookLogIDFieldInvalid = "egress-webhook-log-id-field-invalid"
	ErrEgressWebhookPathInvalid       = "egress-webhook-path-invalid"
)

func IsErrEgressWebhookLogIDFieldInvalid(err error) bool {
	return IsError(err, ErrEgressWebhookLogIDFieldInvalid)
}

func IsErrEgressWebhookPathInvalid(err error) bool {
	return IsError(err, ErrEgressWebhookPathInvalid)
}
