// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrEgressWebhookPathInvalid       = "ERR_KLEV_EGRESS_WEBHOOKS_API_0001"
	ErrEgressWebhookLogIDFieldInvalid = "ERR_KLEV_EGRESS_WEBHOOKS_API_0002"
)

func IsErrEgressWebhookPathInvalid(err error) bool {
	return IsError(err, ErrEgressWebhookPathInvalid)
}

func IsErrEgressWebhookLogIDFieldInvalid(err error) bool {
	return IsError(err, ErrEgressWebhookLogIDFieldInvalid)
}
