// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrEgressWebhookCountLimitedCode    = "egress-webhook-count-limited"
	ErrEgressWebhookMetadataLimitedCode = "egress-webhook-metadata-limited"
	ErrEgressWebhookNotFoundCode        = "egress-webhook-not-found"
	ErrEgressWebhookPayloadInvalidCode  = "egress-webhook-payload-invalid"
)

func IsErrEgressWebhookCountLimited(err error) bool {
	return IsError(err, ErrEgressWebhookCountLimitedCode)
}

func IsErrEgressWebhookMetadataLimited(err error) bool {
	return IsError(err, ErrEgressWebhookMetadataLimitedCode)
}

func IsErrEgressWebhookNotFound(err error) bool {
	return IsError(err, ErrEgressWebhookNotFoundCode)
}

func IsErrEgressWebhookPayloadInvalid(err error) bool {
	return IsError(err, ErrEgressWebhookPayloadInvalidCode)
}
