// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrEgressWebhookLogIDFieldInvalidCode = "egress-webhook-log-id-field-invalid"
	ErrEgressWebhookPathInvalidCode       = "egress-webhook-path-invalid"
)

func IsErrEgressWebhookLogIDFieldInvalid(err error) bool {
	return IsError(err, ErrEgressWebhookLogIDFieldInvalidCode)
}

func IsErrEgressWebhookPathInvalid(err error) bool {
	return IsError(err, ErrEgressWebhookPathInvalidCode)
}
