// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type EgressWebhookID struct{ string }

var nilEgressWebhookID = EgressWebhookID{}

func ParseEgressWebhookID(id string) (EgressWebhookID, error) {
	if err := validate(id, "ewh"); err != nil {
		return nilEgressWebhookID, err
	}
	return EgressWebhookID{id}, nil
}

func (id EgressWebhookID) String() string {
	return id.string
}

func (id EgressWebhookID) IDValue() string {
	return id.string
}

func (id EgressWebhookID) MarshalText() ([]byte, error) {
	return []byte(id.string), nil
}

func (id *EgressWebhookID) UnmarshalText(text []byte) error {
	str := string(text)
	if len(str) == 0 {
		return nil
	}

	if err := validate(str, "ewh"); err != nil {
		return err
	}

	id.string = str
	return nil
}
