// Code generated by 'gen-errors'; DO NOT EDIT
package klev

import (
	"fmt"
)

func ErrEgressWebhookPayloadInvalid(s string, valid string) error {
	return &APIError{
		Code:    "egress-webhook-payload-invalid",
		Message: fmt.Sprintf("'%s' is not a valid egress webhook payload. Must be one of '%s'", s, valid),
	}
}
