// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrEgressWebhookNotFound       = "ERR_KLEV_EGRESS_WEBHOOKS_0001"
	ErrEgressWebhookMaxMetadata    = "ERR_KLEV_EGRESS_WEBHOOKS_0002"
	ErrEgressWebhookMaxCount       = "ERR_KLEV_EGRESS_WEBHOOKS_0003"
	ErrEgressWebhookInvalidPayload = "ERR_KLEV_EGRESS_WEBHOOKS_0004"
)

func IsErrEgressWebhookNotFound(err error) bool {
	return IsError(err, ErrEgressWebhookNotFound)
}

func IsErrEgressWebhookMaxMetadata(err error) bool {
	return IsError(err, ErrEgressWebhookMaxMetadata)
}

func IsErrEgressWebhookMaxCount(err error) bool {
	return IsError(err, ErrEgressWebhookMaxCount)
}

func IsErrEgressWebhookInvalidPayload(err error) bool {
	return IsError(err, ErrEgressWebhookInvalidPayload)
}
