// Code generated by 'make gen-errors'; DO NOT EDIT
package api

// Internal errors
var (
	ErrInternalServerError      = "ERR_KLEV_INTERNAL_0001"
	ErrInternalMaintenanceError = "ERR_KLEV_INTERNAL_0002"
)

// ID errors
var (
	ErrIDInvalidFormat = "ERR_KLEV_ID_0001"
	ErrIDInvalidPrefix = "ERR_KLEV_ID_0002"
	ErrIDInvalidSuffix = "ERR_KLEV_ID_0003"
)

// API errors
var (
	ErrAPIContentTypeInvalid             = "ERR_KLEV_API_0001"
	ErrAPIAuthorizationHeaderInvalid     = "ERR_KLEV_API_0002"
	ErrAPISubscriptionMissing            = "ERR_KLEV_API_0004"
	ErrAPIPathNotFound                   = "ERR_KLEV_API_0005"
	ErrAPIMethodNotAllowed               = "ERR_KLEV_API_0006"
	ErrAPITokenPathInvalid               = "ERR_KLEV_API_0007"
	ErrAPILogPathInvalid                 = "ERR_KLEV_API_0008"
	ErrAPIInvalidJson                    = "ERR_KLEV_API_0009"
	ErrAPIOffsetParameterInvalid         = "ERR_KLEV_API_0010"
	ErrAPILenParameterInvalid            = "ERR_KLEV_API_0011"
	ErrAPIEncodingParameterInvalid       = "ERR_KLEV_API_0012"
	ErrAPIIngressWebhookPathInvalid      = "ERR_KLEV_API_0013"
	ErrAPIACLInsufficientPermissions     = "ERR_KLEV_API_0014"
	ErrAPIACLItemFormatInvalid           = "ERR_KLEV_API_0015"
	ErrAPIACLSubjectInvalid              = "ERR_KLEV_API_0016"
	ErrAPIACLActionInvalid               = "ERR_KLEV_API_0017"
	ErrAPIACLObjectActionInvalid         = "ERR_KLEV_API_0018"
	ErrAPIACLObjectTokenInvalid          = "ERR_KLEV_API_0019"
	ErrAPIACLObjectLogInvalid            = "ERR_KLEV_API_0020"
	ErrAPIACLObjectIngressWebhookInvalid = "ERR_KLEV_API_0021"
	ErrAPIOffsetPathInvalid              = "ERR_KLEV_API_0022"
	ErrAPIOffsetLogMismatch              = "ERR_KLEV_API_0023"
	ErrAPIACLObjectOffsetInvalid         = "ERR_KLEV_API_0024"
	ErrAPIPollParameterInvalid           = "ERR_KLEV_API_0025"
	ErrAPIACLObjectEgressWebhookInvalid  = "ERR_KLEV_API_0026"
	ErrAPIEgressWebhookPathInvalid       = "ERR_KLEV_API_0027"
	ErrAPIContentTypeMissing             = "ERR_KLEV_API_0029"
	ErrAPIAuthorizationHeaderMissing     = "ERR_KLEV_API_0030"
	ErrAPIEncodingInvalid                = "ERR_KLEV_API_0031"
	ErrAPIEncodingFieldInvalid           = "ERR_KLEV_API_0032"
	ErrAPIOffsetIDParameterInvalid       = "ERR_KLEV_API_0033"
	ErrAPILogIDFieldInvalid              = "ERR_KLEV_API_0034"
	ErrAPILogIDParameterInvalid          = "ERR_KLEV_API_0035"
	ErrAPIAuthenticationFailed           = "ERR_KLEV_API_0036"
)

// APIWebhooks errors
var (
	ErrAPIWebhooksPathNotFound              = "ERR_KLEV_API_WEBHOOKS_0001"
	ErrAPIWebhooksIngressWebhookPathInvalid = "ERR_KLEV_API_WEBHOOKS_0002"
)

// Logs errors
var (
	ErrLogsNotFound         = "ERR_KLEV_LOGS_0001"
	ErrLogsMaxMetadata      = "ERR_KLEV_LOGS_0002"
	ErrLogsAgeCompactExpire = "ERR_KLEV_LOGS_0003"
	ErrLogsMaxCount         = "ERR_KLEV_LOGS_0004"
)

// Messages errors
var (
	ErrMessagesMaxPublish            = "ERR_KLEV_MESSAGES_0001"
	ErrMessagesMaxKey                = "ERR_KLEV_MESSAGES_0002"
	ErrMessagesMaxValue              = "ERR_KLEV_MESSAGES_0003"
	ErrMessagesMaxConsume            = "ERR_KLEV_MESSAGES_0004"
	ErrMessagesConsumeInvalid        = "ERR_KLEV_MESSAGES_0005"
	ErrMessagesGetByOffsetNotFound   = "ERR_KLEV_MESSAGES_0006"
	ErrMessagesGetByOffsetInvalid    = "ERR_KLEV_MESSAGES_0007"
	ErrMessagesGetByKeyNotCompacting = "ERR_KLEV_MESSAGES_0008"
	ErrMessagesGetByKeyNotFound      = "ERR_KLEV_MESSAGES_0009"
	ErrMessagesMaxPoll               = "ERR_KLEV_MESSAGES_0010"
)

// Offsets errors
var (
	ErrOffsetsNotFound         = "ERR_KLEV_OFFSETS_0001"
	ErrOffsetsMaxMetadata      = "ERR_KLEV_OFFSETS_0002"
	ErrOffsetsMaxValueMetadata = "ERR_KLEV_OFFSETS_0003"
	ErrOffsetsMaxCount         = "ERR_KLEV_OFFSETS_0004"
)

// Tokens errors
var (
	ErrTokensNotFound          = "ERR_KLEV_TOKENS_0001"
	ErrTokensMaxMetadata       = "ERR_KLEV_TOKENS_0003"
	ErrTokensMaxCount          = "ERR_KLEV_TOKENS_0004"
	ErrTokensAuthInvalidFormat = "ERR_KLEV_TOKENS_0005"
	ErrTokensAuthInvalidID     = "ERR_KLEV_TOKENS_0006"
	ErrTokensAuthInvalid       = "ERR_KLEV_TOKENS_0007"
)

// IngressWebhooks errors
var (
	ErrIngressWebhooksIngressNotFound    = "ERR_KLEV_INGRESS_WEBHOOKS_0001"
	ErrIngressWebhooksIngressMaxMetadata = "ERR_KLEV_INGRESS_WEBHOOKS_0002"
	ErrIngressWebhooksIngressInvalidType = "ERR_KLEV_INGRESS_WEBHOOKS_0003"
	ErrIngressWebhooksIngressMaxCount    = "ERR_KLEV_INGRESS_WEBHOOKS_0004"
)

// EgressWebhooks errors
var (
	ErrEgressWebhooksEgressNotFound       = "ERR_KLEV_EGRESS_WEBHOOKS_0001"
	ErrEgressWebhooksEgressMaxMetadata    = "ERR_KLEV_EGRESS_WEBHOOKS_0002"
	ErrEgressWebhooksEgressMaxCount       = "ERR_KLEV_EGRESS_WEBHOOKS_0003"
	ErrEgressWebhooksEgressInvalidPayload = "ERR_KLEV_EGRESS_WEBHOOKS_0004"
)
