// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrFilterNotFound     = "ERR_KLEV_FILTERS_0001"
	ErrFilterMaxMetadata  = "ERR_KLEV_FILTERS_0002"
	ErrFilterMaxCount     = "ERR_KLEV_FILTERS_0003"
	ErrFilterCompileError = "ERR_KLEV_FILTERS_0004"
	ErrFilterTypeError    = "ERR_KLEV_FILTERS_0005"
)

func IsErrFilterNotFound(err error) bool {
	return IsError(err, ErrFilterNotFound)
}

func IsErrFilterMaxMetadata(err error) bool {
	return IsError(err, ErrFilterMaxMetadata)
}

func IsErrFilterMaxCount(err error) bool {
	return IsError(err, ErrFilterMaxCount)
}

func IsErrFilterCompileError(err error) bool {
	return IsError(err, ErrFilterCompileError)
}

func IsErrFilterTypeError(err error) bool {
	return IsError(err, ErrFilterTypeError)
}
