// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type FilterID struct{ string }

var nilFilterID = FilterID{}

func ParseFilterID(id string) (FilterID, error) {
	if err := validate(id, "trf"); err != nil {
		return nilFilterID, err
	}
	return FilterID{id}, nil
}

func (id FilterID) String() string {
	return id.string
}

func (id FilterID) IDValue() string {
	return id.string
}

func (id FilterID) MarshalText() ([]byte, error) {
	return []byte(id.string), nil
}

func (id *FilterID) UnmarshalText(text []byte) error {
	str := string(text)
	if len(str) == 0 {
		return nil
	}

	if err := validate(str, "trf"); err != nil {
		return err
	}

	id.string = str
	return nil
}
