// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrFilterPathInvalid          = "ERR_KLEV_FILTERS_API_0001"
	ErrFilterSourceIDFieldInvalid = "ERR_KLEV_FILTERS_API_0002"
	ErrFilterTargetIDFieldInvalid = "ERR_KLEV_FILTERS_API_0003"
)

func IsErrFilterPathInvalid(err error) bool {
	return IsError(err, ErrFilterPathInvalid)
}

func IsErrFilterSourceIDFieldInvalid(err error) bool {
	return IsError(err, ErrFilterSourceIDFieldInvalid)
}

func IsErrFilterTargetIDFieldInvalid(err error) bool {
	return IsError(err, ErrFilterTargetIDFieldInvalid)
}
