// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type FilterID string

func ParseFilterID(id string) (FilterID, error) {
	if err := validate(id, "trf"); err != nil {
		return FilterID(""), err
	}
	return FilterID(id), nil
}
