// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrFilterPathInvalidCode          = "filter-path-invalid"
	ErrFilterSourceIDFieldInvalidCode = "filter-source-id-field-invalid"
	ErrFilterTargetIDFieldInvalidCode = "filter-target-id-field-invalid"
)

func IsErrFilterPathInvalid(err error) bool {
	return IsError(err, ErrFilterPathInvalidCode)
}

func IsErrFilterSourceIDFieldInvalid(err error) bool {
	return IsError(err, ErrFilterSourceIDFieldInvalidCode)
}

func IsErrFilterTargetIDFieldInvalid(err error) bool {
	return IsError(err, ErrFilterTargetIDFieldInvalidCode)
}
