// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrFilterCompileFailed   = "filter-compile-failed"
	ErrFilterCountLimited    = "filter-count-limited"
	ErrFilterMetadataLimited = "filter-metadata-limited"
	ErrFilterNotFound        = "filter-not-found"
	ErrFilterTypeNotBool     = "filter-type-not-bool"
)

func IsErrFilterCompileFailed(err error) bool {
	return IsError(err, ErrFilterCompileFailed)
}

func IsErrFilterCountLimited(err error) bool {
	return IsError(err, ErrFilterCountLimited)
}

func IsErrFilterMetadataLimited(err error) bool {
	return IsError(err, ErrFilterMetadataLimited)
}

func IsErrFilterNotFound(err error) bool {
	return IsError(err, ErrFilterNotFound)
}

func IsErrFilterTypeNotBool(err error) bool {
	return IsError(err, ErrFilterTypeNotBool)
}
