// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrFilterPathInvalid          = "filter-path-invalid"
	ErrFilterSourceIDFieldInvalid = "filter-source-id-field-invalid"
	ErrFilterTargetIDFieldInvalid = "filter-target-id-field-invalid"
)

func IsErrFilterPathInvalid(err error) bool {
	return IsError(err, ErrFilterPathInvalid)
}

func IsErrFilterSourceIDFieldInvalid(err error) bool {
	return IsError(err, ErrFilterSourceIDFieldInvalid)
}

func IsErrFilterTargetIDFieldInvalid(err error) bool {
	return IsError(err, ErrFilterTargetIDFieldInvalid)
}
