// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrFilterCompileFailedCode   = "filter-compile-failed"
	ErrFilterCountLimitedCode    = "filter-count-limited"
	ErrFilterMetadataLimitedCode = "filter-metadata-limited"
	ErrFilterNotFoundCode        = "filter-not-found"
	ErrFilterTypeNotBoolCode     = "filter-type-not-bool"
)

func IsErrFilterCompileFailed(err error) bool {
	return IsError(err, ErrFilterCompileFailedCode)
}

func IsErrFilterCountLimited(err error) bool {
	return IsError(err, ErrFilterCountLimitedCode)
}

func IsErrFilterMetadataLimited(err error) bool {
	return IsError(err, ErrFilterMetadataLimitedCode)
}

func IsErrFilterNotFound(err error) bool {
	return IsError(err, ErrFilterNotFoundCode)
}

func IsErrFilterTypeNotBool(err error) bool {
	return IsError(err, ErrFilterTypeNotBoolCode)
}
