// Code generated by 'gen-errors'; DO NOT EDIT
package klev

import (
	"fmt"
)

func ErrIDInvalidFormat(id string) error {
	return &APIError{
		Code:    "id-invalid-format",
		Message: fmt.Sprintf("'%s' doesn't match 'prefix_suffix' format, missing '_'", id),
	}
}

func ErrIDInvalidPrefix(id string, actual string, expected string) error {
	return &APIError{
		Code:    "id-invalid-prefix",
		Message: fmt.Sprintf("'%s' prefix '%s' doesn't match expected prefix '%s'", id, actual, expected),
	}
}

func ErrIDInvalidSuffix(id string, actual string) error {
	return &APIError{
		Code:    "id-invalid-suffix",
		Message: fmt.Sprintf("'%s' suffix '%s' is not a valid KSUID", id, actual),
	}
}

func ErrIDInvalidSuffixLen(id string, actual string) error {
	return &APIError{
		Code:    "id-invalid-suffix-len",
		Message: fmt.Sprintf("'%s' suffix '%s' is not expected length=27", id, actual),
	}
}
