// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

import (
	"fmt"
)

func ErrInvalidIDFormat(id string) error {
	return &APIError{
		Code:    "ERR_KLEV_ID_0001",
		Message: "Invalid ID format",
		Details: fmt.Sprintf("'%s' doesn't match 'prefix_suffix' format, missing '_'", id),
	}
}

func ErrInvalidIDPrefix(id string, actual string, expected string) error {
	return &APIError{
		Code:    "ERR_KLEV_ID_0002",
		Message: "Invalid ID prefix",
		Details: fmt.Sprintf("'%s' prefix '%s' doesn't match expected prefix '%s'", id, actual, expected),
	}
}

func ErrInvalidIDSuffix(id string, actual string) error {
	return &APIError{
		Code:    "ERR_KLEV_ID_0003",
		Message: "Invalid ID suffix",
		Details: fmt.Sprintf("'%s' suffix '%s' is not a valid KSUID", id, actual),
	}
}

func ErrInvalidIDSuffixLen(id string, actual string) error {
	return &APIError{
		Code:    "ERR_KLEV_ID_0004",
		Message: "Invalid ID suffix length",
		Details: fmt.Sprintf("'%s' suffix '%s' is not expected length=27", id, actual),
	}
}
