// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrIngressWebhookCountLimited    = "ingress-webhook-count-limited"
	ErrIngressWebhookMetadataLimited = "ingress-webhook-metadata-limited"
	ErrIngressWebhookNotFound        = "ingress-webhook-not-found"
	ErrIngressWebhookTypeInvalid     = "ingress-webhook-type-invalid"
)

func IsErrIngressWebhookCountLimited(err error) bool {
	return IsError(err, ErrIngressWebhookCountLimited)
}

func IsErrIngressWebhookMetadataLimited(err error) bool {
	return IsError(err, ErrIngressWebhookMetadataLimited)
}

func IsErrIngressWebhookNotFound(err error) bool {
	return IsError(err, ErrIngressWebhookNotFound)
}

func IsErrIngressWebhookTypeInvalid(err error) bool {
	return IsError(err, ErrIngressWebhookTypeInvalid)
}
