// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrIngressWebhookNotFound    = "ERR_KLEV_INGRESS_WEBHOOKS_0001"
	ErrIngressWebhookMaxMetadata = "ERR_KLEV_INGRESS_WEBHOOKS_0002"
	ErrIngressWebhookInvalidType = "ERR_KLEV_INGRESS_WEBHOOKS_0003"
	ErrIngressWebhookMaxCount    = "ERR_KLEV_INGRESS_WEBHOOKS_0004"
)

func IsErrIngressWebhookNotFound(err error) bool {
	return IsError(err, ErrIngressWebhookNotFound)
}

func IsErrIngressWebhookMaxMetadata(err error) bool {
	return IsError(err, ErrIngressWebhookMaxMetadata)
}

func IsErrIngressWebhookInvalidType(err error) bool {
	return IsError(err, ErrIngressWebhookInvalidType)
}

func IsErrIngressWebhookMaxCount(err error) bool {
	return IsError(err, ErrIngressWebhookMaxCount)
}
