// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type IngressWebhookID string

func ParseIngressWebhookID(id string) (IngressWebhookID, error) {
	if err := validate(id, "iwh"); err != nil {
		return IngressWebhookID(""), err
	}
	return IngressWebhookID(id), nil
}
