// Code generated by 'make gen-errors'; DO NOT EDIT
package api

import (
	"fmt"
)

func ErrKlevNotSigned() error {
	return &ErrorOut{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0001",
		Message: "'X-Klev-Signature' header is missing",
	}
}

func ErrKlevTimestampInvalid(ts string) error {
	return &ErrorOut{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0002",
		Message: fmt.Sprintf("not a valid timestamp: %s", ts),
	}
}

func ErrKlevTimestampExpired(ts string) error {
	return &ErrorOut{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0003",
		Message: fmt.Sprintf("timestamp is too old: %s", ts),
	}
}

func ErrKlevSignatureTimeMissing(h string) error {
	return &ErrorOut{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0004",
		Message: fmt.Sprintf("'X-Klev-Signature' header is missing time: %s", h),
	}
}

func ErrKlevSignatureMissing(h string) error {
	return &ErrorOut{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0005",
		Message: fmt.Sprintf("'X-Klev-Signature' header is missing signature: %s", h),
	}
}

func ErrKlevSignatureMismatch() error {
	return &ErrorOut{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0006",
		Message: "message signature did not match",
	}
}

func ErrKlevInvalidContentType() error {
	return &ErrorOut{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0007",
		Message: "'Content-Type: application/json' header is required",
	}
}
