// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrIngressWebhookCountLimitedCode    = "ingress-webhook-count-limited"
	ErrIngressWebhookMetadataLimitedCode = "ingress-webhook-metadata-limited"
	ErrIngressWebhookNotFoundCode        = "ingress-webhook-not-found"
	ErrIngressWebhookTypeInvalidCode     = "ingress-webhook-type-invalid"
)

func IsErrIngressWebhookCountLimited(err error) bool {
	return IsError(err, ErrIngressWebhookCountLimitedCode)
}

func IsErrIngressWebhookMetadataLimited(err error) bool {
	return IsError(err, ErrIngressWebhookMetadataLimitedCode)
}

func IsErrIngressWebhookNotFound(err error) bool {
	return IsError(err, ErrIngressWebhookNotFoundCode)
}

func IsErrIngressWebhookTypeInvalid(err error) bool {
	return IsError(err, ErrIngressWebhookTypeInvalidCode)
}
