// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type IngressWebhookID struct{ string }

var nilIngressWebhookID = IngressWebhookID{}

func ParseIngressWebhookID(id string) (IngressWebhookID, error) {
	if err := validate(id, "iwh"); err != nil {
		return nilIngressWebhookID, err
	}
	return IngressWebhookID{id}, nil
}

func (id IngressWebhookID) String() string {
	return id.string
}

func (id IngressWebhookID) IDValue() string {
	return id.string
}

func (id IngressWebhookID) MarshalText() ([]byte, error) {
	return []byte(id.string), nil
}

func (id *IngressWebhookID) UnmarshalText(text []byte) error {
	str := string(text)
	if len(str) == 0 {
		return nil
	}

	if err := validate(str, "iwh"); err != nil {
		return err
	}

	id.string = str
	return nil
}
