// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrIngressWebhookLogIDFieldInvalidCode = "ingress-webhook-log-id-field-invalid"
	ErrIngressWebhookPathInvalidCode       = "ingress-webhook-path-invalid"
)

func IsErrIngressWebhookLogIDFieldInvalid(err error) bool {
	return IsError(err, ErrIngressWebhookLogIDFieldInvalidCode)
}

func IsErrIngressWebhookPathInvalid(err error) bool {
	return IsError(err, ErrIngressWebhookPathInvalidCode)
}
