// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrMessagesClosePublishedCode = "messages-close-published"
	ErrMessagesLimitPublishedCode = "messages-limit-published"
)

func IsErrMessagesClosePublished(err error) bool {
	return IsError(err, ErrMessagesClosePublishedCode)
}

func IsErrMessagesLimitPublished(err error) bool {
	return IsError(err, ErrMessagesLimitPublishedCode)
}
