// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type LogID string

func ParseLogID(id string) (LogID, error) {
	if err := validate(id, "log"); err != nil {
		return LogID(""), err
	}
	return LogID(id), nil
}
