// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrLogPathInvalid = "ERR_KLEV_LOGS_API_0001"
)

func IsErrLogPathInvalid(err error) bool {
	return IsError(err, ErrLogPathInvalid)
}
