// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrLogCompactExpireAgeInvalidCode = "log-compact-expire-age-invalid"
	ErrLogCountLimitedCode            = "log-count-limited"
	ErrLogMetadataLimitedCode         = "log-metadata-limited"
	ErrLogNotFoundCode                = "log-not-found"
)

func IsErrLogCompactExpireAgeInvalid(err error) bool {
	return IsError(err, ErrLogCompactExpireAgeInvalidCode)
}

func IsErrLogCountLimited(err error) bool {
	return IsError(err, ErrLogCountLimitedCode)
}

func IsErrLogMetadataLimited(err error) bool {
	return IsError(err, ErrLogMetadataLimitedCode)
}

func IsErrLogNotFound(err error) bool {
	return IsError(err, ErrLogNotFoundCode)
}
