// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrLogNotFound         = "ERR_KLEV_LOGS_0001"
	ErrLogMaxMetadata      = "ERR_KLEV_LOGS_0002"
	ErrLogAgeCompactExpire = "ERR_KLEV_LOGS_0003"
	ErrLogMaxCount         = "ERR_KLEV_LOGS_0004"
)

func IsErrLogNotFound(err error) bool {
	return IsError(err, ErrLogNotFound)
}

func IsErrLogMaxMetadata(err error) bool {
	return IsError(err, ErrLogMaxMetadata)
}

func IsErrLogAgeCompactExpire(err error) bool {
	return IsError(err, ErrLogAgeCompactExpire)
}

func IsErrLogMaxCount(err error) bool {
	return IsError(err, ErrLogMaxCount)
}
