// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrLogCompactExpireAgeInvalid = "log-compact-expire-age-invalid"
	ErrLogCountLimited            = "log-count-limited"
	ErrLogMetadataLimited         = "log-metadata-limited"
	ErrLogNotFound                = "log-not-found"
)

func IsErrLogCompactExpireAgeInvalid(err error) bool {
	return IsError(err, ErrLogCompactExpireAgeInvalid)
}

func IsErrLogCountLimited(err error) bool {
	return IsError(err, ErrLogCountLimited)
}

func IsErrLogMetadataLimited(err error) bool {
	return IsError(err, ErrLogMetadataLimited)
}

func IsErrLogNotFound(err error) bool {
	return IsError(err, ErrLogNotFound)
}
