// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrMessagePathInvalid                    = "ERR_KLEV_MESSAGES_API_0001"
	ErrMessageLenParameterInvalid            = "ERR_KLEV_MESSAGES_API_0002"
	ErrMessageEncodingInvalid                = "ERR_KLEV_MESSAGES_API_0003"
	ErrMessageEncodingParameterInvalid       = "ERR_KLEV_MESSAGES_API_0004"
	ErrMessageEncodingFieldInvalid           = "ERR_KLEV_MESSAGES_API_0005"
	ErrMessagePollParameterInvalid           = "ERR_KLEV_MESSAGES_API_0006"
	ErrMessageOffsetIDParameterInvalid       = "ERR_KLEV_MESSAGES_API_0007"
	ErrMessageOffsetParameterInvalid         = "ERR_KLEV_MESSAGES_API_0008"
	ErrMessageOffsetLogMismatch              = "ERR_KLEV_MESSAGES_API_0009"
	ErrMessageTrimSecondsParameterInvalid    = "ERR_KLEV_MESSAGES_API_0010"
	ErrMessageTrimSizeParameterInvalid       = "ERR_KLEV_MESSAGES_API_0011"
	ErrMessageTrimCountParameterInvalid      = "ERR_KLEV_MESSAGES_API_0012"
	ErrMessageCompactSecondsParameterInvalid = "ERR_KLEV_MESSAGES_API_0013"
	ErrMessageExpireSecondsParameterInvalid  = "ERR_KLEV_MESSAGES_API_0014"
)

func IsErrMessagePathInvalid(err error) bool {
	return IsError(err, ErrMessagePathInvalid)
}

func IsErrMessageLenParameterInvalid(err error) bool {
	return IsError(err, ErrMessageLenParameterInvalid)
}

func IsErrMessageEncodingInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingInvalid)
}

func IsErrMessageEncodingParameterInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingParameterInvalid)
}

func IsErrMessageEncodingFieldInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingFieldInvalid)
}

func IsErrMessagePollParameterInvalid(err error) bool {
	return IsError(err, ErrMessagePollParameterInvalid)
}

func IsErrMessageOffsetIDParameterInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetIDParameterInvalid)
}

func IsErrMessageOffsetParameterInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetParameterInvalid)
}

func IsErrMessageOffsetLogMismatch(err error) bool {
	return IsError(err, ErrMessageOffsetLogMismatch)
}

func IsErrMessageTrimSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimSecondsParameterInvalid)
}

func IsErrMessageTrimSizeParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimSizeParameterInvalid)
}

func IsErrMessageTrimCountParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimCountParameterInvalid)
}

func IsErrMessageCompactSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageCompactSecondsParameterInvalid)
}

func IsErrMessageExpireSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageExpireSecondsParameterInvalid)
}
