// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrMessageCompactSecondsParameterInvalid = "message-compact-seconds-parameter-invalid"
	ErrMessageEncodingFieldInvalid           = "message-encoding-field-invalid"
	ErrMessageEncodingInvalid                = "message-encoding-invalid"
	ErrMessageEncodingParameterInvalid       = "message-encoding-parameter-invalid"
	ErrMessageExpireSecondsParameterInvalid  = "message-expire-seconds-parameter-invalid"
	ErrMessageLenParameterInvalid            = "message-len-parameter-invalid"
	ErrMessageOffsetIDParameterInvalid       = "message-offset-id-parameter-invalid"
	ErrMessageOffsetLogMismatch              = "message-offset-log-mismatch"
	ErrMessageOffsetParameterInvalid         = "message-offset-parameter-invalid"
	ErrMessagePathInvalid                    = "message-path-invalid"
	ErrMessagePollParameterInvalid           = "message-poll-parameter-invalid"
	ErrMessageTrimCountParameterInvalid      = "message-trim-count-parameter-invalid"
	ErrMessageTrimSecondsParameterInvalid    = "message-trim-seconds-parameter-invalid"
	ErrMessageTrimSizeParameterInvalid       = "message-trim-size-parameter-invalid"
)

func IsErrMessageCompactSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageCompactSecondsParameterInvalid)
}

func IsErrMessageEncodingFieldInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingFieldInvalid)
}

func IsErrMessageEncodingInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingInvalid)
}

func IsErrMessageEncodingParameterInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingParameterInvalid)
}

func IsErrMessageExpireSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageExpireSecondsParameterInvalid)
}

func IsErrMessageLenParameterInvalid(err error) bool {
	return IsError(err, ErrMessageLenParameterInvalid)
}

func IsErrMessageOffsetIDParameterInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetIDParameterInvalid)
}

func IsErrMessageOffsetLogMismatch(err error) bool {
	return IsError(err, ErrMessageOffsetLogMismatch)
}

func IsErrMessageOffsetParameterInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetParameterInvalid)
}

func IsErrMessagePathInvalid(err error) bool {
	return IsError(err, ErrMessagePathInvalid)
}

func IsErrMessagePollParameterInvalid(err error) bool {
	return IsError(err, ErrMessagePollParameterInvalid)
}

func IsErrMessageTrimCountParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimCountParameterInvalid)
}

func IsErrMessageTrimSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimSecondsParameterInvalid)
}

func IsErrMessageTrimSizeParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimSizeParameterInvalid)
}
