// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrMessageCompactSecondsParameterInvalidCode = "message-compact-seconds-parameter-invalid"
	ErrMessageEncodingFieldInvalidCode           = "message-encoding-field-invalid"
	ErrMessageEncodingInvalidCode                = "message-encoding-invalid"
	ErrMessageEncodingParameterInvalidCode       = "message-encoding-parameter-invalid"
	ErrMessageExpireSecondsParameterInvalidCode  = "message-expire-seconds-parameter-invalid"
	ErrMessageLenParameterInvalidCode            = "message-len-parameter-invalid"
	ErrMessageOffsetIDParameterInvalidCode       = "message-offset-id-parameter-invalid"
	ErrMessageOffsetLogMismatchCode              = "message-offset-log-mismatch"
	ErrMessageOffsetParameterInvalidCode         = "message-offset-parameter-invalid"
	ErrMessagePathInvalidCode                    = "message-path-invalid"
	ErrMessagePollParameterInvalidCode           = "message-poll-parameter-invalid"
	ErrMessageTrimCountParameterInvalidCode      = "message-trim-count-parameter-invalid"
	ErrMessageTrimSecondsParameterInvalidCode    = "message-trim-seconds-parameter-invalid"
	ErrMessageTrimSizeParameterInvalidCode       = "message-trim-size-parameter-invalid"
)

func IsErrMessageCompactSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageCompactSecondsParameterInvalidCode)
}

func IsErrMessageEncodingFieldInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingFieldInvalidCode)
}

func IsErrMessageEncodingInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingInvalidCode)
}

func IsErrMessageEncodingParameterInvalid(err error) bool {
	return IsError(err, ErrMessageEncodingParameterInvalidCode)
}

func IsErrMessageExpireSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageExpireSecondsParameterInvalidCode)
}

func IsErrMessageLenParameterInvalid(err error) bool {
	return IsError(err, ErrMessageLenParameterInvalidCode)
}

func IsErrMessageOffsetIDParameterInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetIDParameterInvalidCode)
}

func IsErrMessageOffsetLogMismatch(err error) bool {
	return IsError(err, ErrMessageOffsetLogMismatchCode)
}

func IsErrMessageOffsetParameterInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetParameterInvalidCode)
}

func IsErrMessagePathInvalid(err error) bool {
	return IsError(err, ErrMessagePathInvalidCode)
}

func IsErrMessagePollParameterInvalid(err error) bool {
	return IsError(err, ErrMessagePollParameterInvalidCode)
}

func IsErrMessageTrimCountParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimCountParameterInvalidCode)
}

func IsErrMessageTrimSecondsParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimSecondsParameterInvalidCode)
}

func IsErrMessageTrimSizeParameterInvalid(err error) bool {
	return IsError(err, ErrMessageTrimSizeParameterInvalidCode)
}
