// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrMessageConsumeLimitedCode = "message-consume-limited"
	ErrMessageKeyLimitedCode     = "message-key-limited"
	ErrMessageKeyNotFoundCode    = "message-key-not-found"
	ErrMessageNotCompactingCode  = "message-not-compacting"
	ErrMessageOffsetInvalidCode  = "message-offset-invalid"
	ErrMessageOffsetNotFoundCode = "message-offset-not-found"
	ErrMessagePollLimitedCode    = "message-poll-limited"
	ErrMessagePublishLimitedCode = "message-publish-limited"
	ErrMessageValueLimitedCode   = "message-value-limited"
)

func IsErrMessageConsumeLimited(err error) bool {
	return IsError(err, ErrMessageConsumeLimitedCode)
}

func IsErrMessageKeyLimited(err error) bool {
	return IsError(err, ErrMessageKeyLimitedCode)
}

func IsErrMessageKeyNotFound(err error) bool {
	return IsError(err, ErrMessageKeyNotFoundCode)
}

func IsErrMessageNotCompacting(err error) bool {
	return IsError(err, ErrMessageNotCompactingCode)
}

func IsErrMessageOffsetInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetInvalidCode)
}

func IsErrMessageOffsetNotFound(err error) bool {
	return IsError(err, ErrMessageOffsetNotFoundCode)
}

func IsErrMessagePollLimited(err error) bool {
	return IsError(err, ErrMessagePollLimitedCode)
}

func IsErrMessagePublishLimited(err error) bool {
	return IsError(err, ErrMessagePublishLimitedCode)
}

func IsErrMessageValueLimited(err error) bool {
	return IsError(err, ErrMessageValueLimitedCode)
}
