// Code generated by 'gen-errors'; DO NOT EDIT
package klev

import (
	"fmt"
)

func ErrMessageEncodingInvalid(encoding string, valid string) error {
	return &APIError{
		Code:    "message-encoding-invalid",
		Message: fmt.Sprintf("'%s' is not a valid encoding. Must be one of '%s'", encoding, valid),
	}
}
