// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrMessageConsumeLimited = "message-consume-limited"
	ErrMessageKeyLimited     = "message-key-limited"
	ErrMessageKeyNotFound    = "message-key-not-found"
	ErrMessageNotCompacting  = "message-not-compacting"
	ErrMessageOffsetInvalid  = "message-offset-invalid"
	ErrMessageOffsetNotFound = "message-offset-not-found"
	ErrMessagePollLimited    = "message-poll-limited"
	ErrMessagePublishLimited = "message-publish-limited"
	ErrMessageValueLimited   = "message-value-limited"
)

func IsErrMessageConsumeLimited(err error) bool {
	return IsError(err, ErrMessageConsumeLimited)
}

func IsErrMessageKeyLimited(err error) bool {
	return IsError(err, ErrMessageKeyLimited)
}

func IsErrMessageKeyNotFound(err error) bool {
	return IsError(err, ErrMessageKeyNotFound)
}

func IsErrMessageNotCompacting(err error) bool {
	return IsError(err, ErrMessageNotCompacting)
}

func IsErrMessageOffsetInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetInvalid)
}

func IsErrMessageOffsetNotFound(err error) bool {
	return IsError(err, ErrMessageOffsetNotFound)
}

func IsErrMessagePollLimited(err error) bool {
	return IsError(err, ErrMessagePollLimited)
}

func IsErrMessagePublishLimited(err error) bool {
	return IsError(err, ErrMessagePublishLimited)
}

func IsErrMessageValueLimited(err error) bool {
	return IsError(err, ErrMessageValueLimited)
}
