// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrMessageMaxPublish     = "ERR_KLEV_MESSAGES_0001"
	ErrMessageMaxKey         = "ERR_KLEV_MESSAGES_0002"
	ErrMessageMaxValue       = "ERR_KLEV_MESSAGES_0003"
	ErrMessageMaxConsume     = "ERR_KLEV_MESSAGES_0004"
	ErrMessageOffsetNotFound = "ERR_KLEV_MESSAGES_0005"
	ErrMessageOffsetInvalid  = "ERR_KLEV_MESSAGES_0006"
	ErrMessageNotCompacting  = "ERR_KLEV_MESSAGES_0007"
	ErrMessageKeyNotFound    = "ERR_KLEV_MESSAGES_0008"
	ErrMessageMaxPoll        = "ERR_KLEV_MESSAGES_0009"
)

func IsErrMessageMaxPublish(err error) bool {
	return IsError(err, ErrMessageMaxPublish)
}

func IsErrMessageMaxKey(err error) bool {
	return IsError(err, ErrMessageMaxKey)
}

func IsErrMessageMaxValue(err error) bool {
	return IsError(err, ErrMessageMaxValue)
}

func IsErrMessageMaxConsume(err error) bool {
	return IsError(err, ErrMessageMaxConsume)
}

func IsErrMessageOffsetNotFound(err error) bool {
	return IsError(err, ErrMessageOffsetNotFound)
}

func IsErrMessageOffsetInvalid(err error) bool {
	return IsError(err, ErrMessageOffsetInvalid)
}

func IsErrMessageNotCompacting(err error) bool {
	return IsError(err, ErrMessageNotCompacting)
}

func IsErrMessageKeyNotFound(err error) bool {
	return IsError(err, ErrMessageKeyNotFound)
}

func IsErrMessageMaxPoll(err error) bool {
	return IsError(err, ErrMessageMaxPoll)
}
