// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrOffsetCountLimitedCode         = "offset-count-limited"
	ErrOffsetMetadataLimitedCode      = "offset-metadata-limited"
	ErrOffsetNotFoundCode             = "offset-not-found"
	ErrOffsetValueMetadataLimitedCode = "offset-value-metadata-limited"
)

func IsErrOffsetCountLimited(err error) bool {
	return IsError(err, ErrOffsetCountLimitedCode)
}

func IsErrOffsetMetadataLimited(err error) bool {
	return IsError(err, ErrOffsetMetadataLimitedCode)
}

func IsErrOffsetNotFound(err error) bool {
	return IsError(err, ErrOffsetNotFoundCode)
}

func IsErrOffsetValueMetadataLimited(err error) bool {
	return IsError(err, ErrOffsetValueMetadataLimitedCode)
}
