// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrOffsetPathInvalid       = "ERR_KLEV_OFFSETS_API_0001"
	ErrOffsetLogIDFieldInvalid = "ERR_KLEV_OFFSETS_API_0002"
)

func IsErrOffsetPathInvalid(err error) bool {
	return IsError(err, ErrOffsetPathInvalid)
}

func IsErrOffsetLogIDFieldInvalid(err error) bool {
	return IsError(err, ErrOffsetLogIDFieldInvalid)
}
