// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrOffsetCountLimited         = "offset-count-limited"
	ErrOffsetMetadataLimited      = "offset-metadata-limited"
	ErrOffsetNotFound             = "offset-not-found"
	ErrOffsetValueMetadataLimited = "offset-value-metadata-limited"
)

func IsErrOffsetCountLimited(err error) bool {
	return IsError(err, ErrOffsetCountLimited)
}

func IsErrOffsetMetadataLimited(err error) bool {
	return IsError(err, ErrOffsetMetadataLimited)
}

func IsErrOffsetNotFound(err error) bool {
	return IsError(err, ErrOffsetNotFound)
}

func IsErrOffsetValueMetadataLimited(err error) bool {
	return IsError(err, ErrOffsetValueMetadataLimited)
}
