// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type OffsetID struct{ string }

var nilOffsetID = OffsetID{}

func ParseOffsetID(id string) (OffsetID, error) {
	if err := validate(id, "off"); err != nil {
		return nilOffsetID, err
	}
	return OffsetID{id}, nil
}

func (id OffsetID) String() string {
	return id.string
}

func (id OffsetID) IDValue() string {
	return id.string
}

func (id OffsetID) MarshalText() ([]byte, error) {
	return []byte(id.string), nil
}

func (id *OffsetID) UnmarshalText(text []byte) error {
	str := string(text)
	if len(str) == 0 {
		return nil
	}

	if err := validate(str, "off"); err != nil {
		return err
	}

	id.string = str
	return nil
}
