// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrOffsetNotFound         = "ERR_KLEV_OFFSETS_0001"
	ErrOffsetMaxMetadata      = "ERR_KLEV_OFFSETS_0002"
	ErrOffsetMaxValueMetadata = "ERR_KLEV_OFFSETS_0003"
	ErrOffsetMaxCount         = "ERR_KLEV_OFFSETS_0004"
)

func IsErrOffsetNotFound(err error) bool {
	return IsError(err, ErrOffsetNotFound)
}

func IsErrOffsetMaxMetadata(err error) bool {
	return IsError(err, ErrOffsetMaxMetadata)
}

func IsErrOffsetMaxValueMetadata(err error) bool {
	return IsError(err, ErrOffsetMaxValueMetadata)
}

func IsErrOffsetMaxCount(err error) bool {
	return IsError(err, ErrOffsetMaxCount)
}
