// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrOffsetLogIDFieldInvalid = "offset-log-id-field-invalid"
	ErrOffsetPathInvalid       = "offset-path-invalid"
)

func IsErrOffsetLogIDFieldInvalid(err error) bool {
	return IsError(err, ErrOffsetLogIDFieldInvalid)
}

func IsErrOffsetPathInvalid(err error) bool {
	return IsError(err, ErrOffsetPathInvalid)
}
