// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrMaintenanceError = "maintenance-error"
	ErrServerError      = "server-error"
)

func IsErrMaintenanceError(err error) bool {
	return IsError(err, ErrMaintenanceError)
}

func IsErrServerError(err error) bool {
	return IsError(err, ErrServerError)
}
