// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrServerError      = "ERR_KLEV_COMMON_0001"
	ErrMaintenanceError = "ERR_KLEV_COMMON_0002"
)

func IsErrServerError(err error) bool {
	return IsError(err, ErrServerError)
}

func IsErrMaintenanceError(err error) bool {
	return IsError(err, ErrMaintenanceError)
}
