// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrMaintenanceErrorCode = "maintenance-error"
	ErrServerErrorCode      = "server-error"
)

func IsErrMaintenanceError(err error) bool {
	return IsError(err, ErrMaintenanceErrorCode)
}

func IsErrServerError(err error) bool {
	return IsError(err, ErrServerErrorCode)
}
