// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrTokenACLItemLimitedCode    = "token-acl-item-limited"
	ErrTokenACLNotAllowedCode     = "token-acl-not-allowed"
	ErrTokenAuthInvalidCode       = "token-auth-invalid"
	ErrTokenAuthInvalidFormatCode = "token-auth-invalid-format"
	ErrTokenAuthInvalidIDCode     = "token-auth-invalid-id"
	ErrTokenCountLimitedCode      = "token-count-limited"
	ErrTokenMetadataLimitedCode   = "token-metadata-limited"
	ErrTokenNotFoundCode          = "token-not-found"
)

func IsErrTokenACLItemLimited(err error) bool {
	return IsError(err, ErrTokenACLItemLimitedCode)
}

func IsErrTokenACLNotAllowed(err error) bool {
	return IsError(err, ErrTokenACLNotAllowedCode)
}

func IsErrTokenAuthInvalid(err error) bool {
	return IsError(err, ErrTokenAuthInvalidCode)
}

func IsErrTokenAuthInvalidFormat(err error) bool {
	return IsError(err, ErrTokenAuthInvalidFormatCode)
}

func IsErrTokenAuthInvalidID(err error) bool {
	return IsError(err, ErrTokenAuthInvalidIDCode)
}

func IsErrTokenCountLimited(err error) bool {
	return IsError(err, ErrTokenCountLimitedCode)
}

func IsErrTokenMetadataLimited(err error) bool {
	return IsError(err, ErrTokenMetadataLimitedCode)
}

func IsErrTokenNotFound(err error) bool {
	return IsError(err, ErrTokenNotFoundCode)
}
