// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrTokenPathInvalid = "ERR_KLEV_TOKENS_API_0001"
)

func IsErrTokenPathInvalid(err error) bool {
	return IsError(err, ErrTokenPathInvalid)
}
