// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type TokenID struct{ string }

var nilTokenID = TokenID{}

func ParseTokenID(id string) (TokenID, error) {
	if err := validate(id, "tok"); err != nil {
		return nilTokenID, err
	}
	return TokenID{id}, nil
}

func (id TokenID) String() string {
	return id.string
}

func (id TokenID) IDValue() string {
	return id.string
}

func (id TokenID) MarshalText() ([]byte, error) {
	return []byte(id.string), nil
}

func (id *TokenID) UnmarshalText(text []byte) error {
	str := string(text)
	if len(str) == 0 {
		return nil
	}

	if err := validate(str, "tok"); err != nil {
		return err
	}

	id.string = str
	return nil
}
