// Code generated by 'gen-objects'; DO NOT EDIT
package klev

type TokenID string

func ParseTokenID(id string) (TokenID, error) {
	if err := validate(id, "tok"); err != nil {
		return TokenID(""), err
	}
	return TokenID(id), nil
}
