// Code generated by 'make gen-errors'; DO NOT EDIT
package klev

const (
	ErrTokenNotFound          = "ERR_KLEV_TOKENS_0001"
	ErrTokenMaxMetadata       = "ERR_KLEV_TOKENS_0002"
	ErrTokenMaxCount          = "ERR_KLEV_TOKENS_0003"
	ErrTokenAuthInvalidFormat = "ERR_KLEV_TOKENS_0004"
	ErrTokenAuthInvalidID     = "ERR_KLEV_TOKENS_0005"
	ErrTokenAuthInvalid       = "ERR_KLEV_TOKENS_0006"
)

func IsErrTokenNotFound(err error) bool {
	return IsError(err, ErrTokenNotFound)
}

func IsErrTokenMaxMetadata(err error) bool {
	return IsError(err, ErrTokenMaxMetadata)
}

func IsErrTokenMaxCount(err error) bool {
	return IsError(err, ErrTokenMaxCount)
}

func IsErrTokenAuthInvalidFormat(err error) bool {
	return IsError(err, ErrTokenAuthInvalidFormat)
}

func IsErrTokenAuthInvalidID(err error) bool {
	return IsError(err, ErrTokenAuthInvalidID)
}

func IsErrTokenAuthInvalid(err error) bool {
	return IsError(err, ErrTokenAuthInvalid)
}
