// Code generated by 'gen-errors'; DO NOT EDIT
package klev

const (
	ErrTokenPathInvalid = "token-path-invalid"
)

func IsErrTokenPathInvalid(err error) bool {
	return IsError(err, ErrTokenPathInvalid)
}
