// Code generated by 'make gen-errors'; DO NOT EDIT
package tokens

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrTokenPathInvalid = "ERR_KLEV_TOKENS_API_0001"
)

func IsErrTokenPathInvalid(err error) bool {
	return errors.IsError(err, ErrTokenPathInvalid)
}
