// Code generated by 'make gen-errors'; DO NOT EDIT
package tokens

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrNotFound          = "ERR_KLEV_TOKENS_0001"
	ErrMaxMetadata       = "ERR_KLEV_TOKENS_0003"
	ErrMaxCount          = "ERR_KLEV_TOKENS_0004"
	ErrAuthInvalidFormat = "ERR_KLEV_TOKENS_0005"
	ErrAuthInvalidID     = "ERR_KLEV_TOKENS_0006"
	ErrAuthInvalid       = "ERR_KLEV_TOKENS_0007"
)

func IsErrNotFound(err error) bool {
	return errors.IsError(err, ErrNotFound)
}

func IsErrMaxMetadata(err error) bool {
	return errors.IsError(err, ErrMaxMetadata)
}

func IsErrMaxCount(err error) bool {
	return errors.IsError(err, ErrMaxCount)
}

func IsErrAuthInvalidFormat(err error) bool {
	return errors.IsError(err, ErrAuthInvalidFormat)
}

func IsErrAuthInvalidID(err error) bool {
	return errors.IsError(err, ErrAuthInvalidID)
}

func IsErrAuthInvalid(err error) bool {
	return errors.IsError(err, ErrAuthInvalid)
}
