// Code generated by 'make gen-errors'; DO NOT EDIT
package messages

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrMaxPublish            = "ERR_KLEV_MESSAGES_0001"
	ErrMaxKey                = "ERR_KLEV_MESSAGES_0002"
	ErrMaxValue              = "ERR_KLEV_MESSAGES_0003"
	ErrMaxConsume            = "ERR_KLEV_MESSAGES_0004"
	ErrConsumeInvalid        = "ERR_KLEV_MESSAGES_0005"
	ErrGetByOffsetNotFound   = "ERR_KLEV_MESSAGES_0006"
	ErrGetByOffsetInvalid    = "ERR_KLEV_MESSAGES_0007"
	ErrGetByKeyNotCompacting = "ERR_KLEV_MESSAGES_0008"
	ErrGetByKeyNotFound      = "ERR_KLEV_MESSAGES_0009"
	ErrMaxPoll               = "ERR_KLEV_MESSAGES_0010"
)

func IsErrMaxPublish(err error) bool {
	return errors.IsError(err, ErrMaxPublish)
}

func IsErrMaxKey(err error) bool {
	return errors.IsError(err, ErrMaxKey)
}

func IsErrMaxValue(err error) bool {
	return errors.IsError(err, ErrMaxValue)
}

func IsErrMaxConsume(err error) bool {
	return errors.IsError(err, ErrMaxConsume)
}

func IsErrConsumeInvalid(err error) bool {
	return errors.IsError(err, ErrConsumeInvalid)
}

func IsErrGetByOffsetNotFound(err error) bool {
	return errors.IsError(err, ErrGetByOffsetNotFound)
}

func IsErrGetByOffsetInvalid(err error) bool {
	return errors.IsError(err, ErrGetByOffsetInvalid)
}

func IsErrGetByKeyNotCompacting(err error) bool {
	return errors.IsError(err, ErrGetByKeyNotCompacting)
}

func IsErrGetByKeyNotFound(err error) bool {
	return errors.IsError(err, ErrGetByKeyNotFound)
}

func IsErrMaxPoll(err error) bool {
	return errors.IsError(err, ErrMaxPoll)
}
