// Code generated by 'make gen-errors'; DO NOT EDIT
package offsets

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrOffsetPathInvalid       = "ERR_KLEV_OFFSETS_API_0001"
	ErrOffsetLogIDFieldInvalid = "ERR_KLEV_OFFSETS_API_0002"
)

func IsErrOffsetPathInvalid(err error) bool {
	return errors.IsError(err, ErrOffsetPathInvalid)
}

func IsErrOffsetLogIDFieldInvalid(err error) bool {
	return errors.IsError(err, ErrOffsetLogIDFieldInvalid)
}
