// Code generated by 'make gen-errors'; DO NOT EDIT
package offsets

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrNotFound         = "ERR_KLEV_OFFSETS_0001"
	ErrMaxMetadata      = "ERR_KLEV_OFFSETS_0002"
	ErrMaxValueMetadata = "ERR_KLEV_OFFSETS_0003"
	ErrMaxCount         = "ERR_KLEV_OFFSETS_0004"
)

func IsErrNotFound(err error) bool {
	return errors.IsError(err, ErrNotFound)
}

func IsErrMaxMetadata(err error) bool {
	return errors.IsError(err, ErrMaxMetadata)
}

func IsErrMaxValueMetadata(err error) bool {
	return errors.IsError(err, ErrMaxValueMetadata)
}

func IsErrMaxCount(err error) bool {
	return errors.IsError(err, ErrMaxCount)
}
