// Code generated by 'make gen-errors'; DO NOT EDIT
package ingress_validate

import (
	"github.com/klev-dev/klev-api-go/errors"

	"fmt"
)

func ErrKlevNotSigned() error {
	return &errors.APIError{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0001",
		Message: "Missing klev signature header",
		Details: "'X-Klev-Signature' header is missing",
	}
}

func ErrKlevTimestampInvalid(ts string) error {
	return &errors.APIError{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0002",
		Message: "Invalid timestamp",
		Details: fmt.Sprintf("'%s' is not a valid timestamp", ts),
	}
}

func ErrKlevTimestampExpired(ts string) error {
	return &errors.APIError{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0003",
		Message: "Expired timestamp",
		Details: fmt.Sprintf("'%s' is no longer valid, too old", ts),
	}
}

func ErrKlevSignatureTimeMissing(h string) error {
	return &errors.APIError{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0004",
		Message: "Signature timestamp missing",
		Details: fmt.Sprintf("'X-Klev-Signature' header is missing timestamp: %s", h),
	}
}

func ErrKlevSignatureMissing(h string) error {
	return &errors.APIError{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0005",
		Message: "Signature missing",
		Details: fmt.Sprintf("'X-Klev-Signature' header is missing signature: %s", h),
	}
}

func ErrKlevSignatureMismatch() error {
	return &errors.APIError{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0006",
		Message: "Signature mismatch",
		Details: "Message signature did not match the expected signature",
	}
}

func ErrKlevInvalidContentTypeJson() error {
	return &errors.APIError{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0007",
		Message: "Invalid content type",
		Details: "'Content-Type: application/json' header is required",
	}
}

func ErrKlevInvalidContentTypeOctet() error {
	return &errors.APIError{
		Code:    "ERR_KLEV_WEBHOOKS_KLEV_0008",
		Message: "Invalid content type",
		Details: "'Content-Type: application/octet-stream' header is required",
	}
}
