// Code generated by 'make gen-errors'; DO NOT EDIT
package egress_webhooks

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrEgressNotFound       = "ERR_KLEV_EGRESS_WEBHOOKS_0001"
	ErrEgressMaxMetadata    = "ERR_KLEV_EGRESS_WEBHOOKS_0002"
	ErrEgressMaxCount       = "ERR_KLEV_EGRESS_WEBHOOKS_0003"
	ErrEgressInvalidPayload = "ERR_KLEV_EGRESS_WEBHOOKS_0004"
)

func IsErrEgressNotFound(err error) bool {
	return errors.IsError(err, ErrEgressNotFound)
}

func IsErrEgressMaxMetadata(err error) bool {
	return errors.IsError(err, ErrEgressMaxMetadata)
}

func IsErrEgressMaxCount(err error) bool {
	return errors.IsError(err, ErrEgressMaxCount)
}

func IsErrEgressInvalidPayload(err error) bool {
	return errors.IsError(err, ErrEgressInvalidPayload)
}
