// Code generated by 'make gen-errors'; DO NOT EDIT
package filters

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrFilterPathInvalid    = "ERR_KLEV_FILTERS_API_0001"
	ErrSourceIDFieldInvalid = "ERR_KLEV_FILTERS_API_0002"
	ErrTargetIDFieldInvalid = "ERR_KLEV_FILTERS_API_0003"
)

func IsErrFilterPathInvalid(err error) bool {
	return errors.IsError(err, ErrFilterPathInvalid)
}

func IsErrSourceIDFieldInvalid(err error) bool {
	return errors.IsError(err, ErrSourceIDFieldInvalid)
}

func IsErrTargetIDFieldInvalid(err error) bool {
	return errors.IsError(err, ErrTargetIDFieldInvalid)
}
