// Code generated by 'make gen-errors'; DO NOT EDIT
package ingress_webhooks

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrIngressWebhookPathInvalid       = "ERR_KLEV_INGRESS_WEBHOOKS_API_0001"
	ErrIngressWebhookLogIDFieldInvalid = "ERR_KLEV_INGRESS_WEBHOOKS_API_0002"
)

func IsErrIngressWebhookPathInvalid(err error) bool {
	return errors.IsError(err, ErrIngressWebhookPathInvalid)
}

func IsErrIngressWebhookLogIDFieldInvalid(err error) bool {
	return errors.IsError(err, ErrIngressWebhookLogIDFieldInvalid)
}
