// Code generated by 'make gen-errors'; DO NOT EDIT
package ingress_webhooks

import "github.com/klev-dev/klev-api-go/errors"

const (
	ErrIngressNotFound    = "ERR_KLEV_INGRESS_WEBHOOKS_0001"
	ErrIngressMaxMetadata = "ERR_KLEV_INGRESS_WEBHOOKS_0002"
	ErrIngressInvalidType = "ERR_KLEV_INGRESS_WEBHOOKS_0003"
	ErrIngressMaxCount    = "ERR_KLEV_INGRESS_WEBHOOKS_0004"
)

func IsErrIngressNotFound(err error) bool {
	return errors.IsError(err, ErrIngressNotFound)
}

func IsErrIngressMaxMetadata(err error) bool {
	return errors.IsError(err, ErrIngressMaxMetadata)
}

func IsErrIngressInvalidType(err error) bool {
	return errors.IsError(err, ErrIngressInvalidType)
}

func IsErrIngressMaxCount(err error) bool {
	return errors.IsError(err, ErrIngressMaxCount)
}
